"""
Jalankan SEKALI untuk generate model_data.js dari data.csv.
Setelah ini kamu tidak perlu python app.py lagi — semuanya jalan di browser.

Cara pakai:
  python export_data.py

Output:
  model_data.js  ->  include di index.html, berisi training data untuk kNN
"""

import csv
import json

CSV_FILE = 'data.csv'
OUTPUT   = 'model_data.js'

print(f"Loading {CSV_FILE}...")
rows = []
with open(CSV_FILE, 'r') as f:
    for row in csv.reader(f):
        if len(row) == 64:
            rows.append([row[0]] + [float(v) for v in row[1:]])

# Hitung distribusi label
from collections import Counter
labels = [r[0] for r in rows]
dist   = Counter(labels)
print(f"Total: {len(rows)} samples")
for label, count in sorted(dist.items()):
    print(f"  {label}: {count}")

# Tulis sebagai JS variable — bisa di-load tanpa fetch (tidak ada CORS issue)
js_content = f"""// Auto-generated by export_data.py — jangan edit manual
// {len(rows)} training samples, {len(set(labels))} emotions
const MODEL_DATA = {json.dumps(rows, separators=(',', ':'))};
const MODEL_LABELS = {json.dumps(sorted(set(labels)))};
"""

with open(OUTPUT, 'w') as f:
    f.write(js_content)

size_kb = len(js_content) / 1024
print(f"\nBerhasil! {OUTPUT} ({size_kb:.0f} KB)")
print("Sekarang buka index.html dengan Live Server — tidak perlu python app.py lagi.")
